#!/usr/bin/env php
<?php

namespace Vividin\I18n;

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$application = new Application();
$application->add(new CsvToPoCommand());
$application->add(new PoToCsvCommand());
$application->run();
